/**
 * Book number -> name/abbreviation table (standard English versification).
 * Index 0 is unused so a book number is its own index.
 */

const BOOKS = [
  null, // 0 = unused
  { num: 1, name: 'Genesis', abbr: 'Gen', aliases: ['ge', 'gn'] },
  { num: 2, name: 'Exodus', abbr: 'Exod', aliases: ['ex', 'exo'] },
  { num: 3, name: 'Leviticus', abbr: 'Lev', aliases: ['le', 'lv'] },
  { num: 4, name: 'Numbers', abbr: 'Num', aliases: ['nu', 'nm'] },
  { num: 5, name: 'Deuteronomy', abbr: 'Deut', aliases: ['de', 'dt'] },
  { num: 6, name: 'Joshua', abbr: 'Josh', aliases: ['jos'] },
  { num: 7, name: 'Judges', abbr: 'Judg', aliases: ['jdg', 'jud'] },
  { num: 8, name: 'Ruth', abbr: 'Ruth', aliases: ['ru', 'rut'] },
  { num: 9, name: '1 Samuel', abbr: '1Sam', aliases: ['1sa'] },
  { num: 10, name: '2 Samuel', abbr: '2Sam', aliases: ['2sa'] },
  { num: 11, name: '1 Kings', abbr: '1Kgs', aliases: ['1ki', '1kin'] },
  { num: 12, name: '2 Kings', abbr: '2Kgs', aliases: ['2ki', '2kin'] },
  { num: 13, name: '1 Chronicles', abbr: '1Chr', aliases: ['1ch', '1chron'] },
  { num: 14, name: '2 Chronicles', abbr: '2Chr', aliases: ['2ch', '2chron'] },
  { num: 15, name: 'Ezra', abbr: 'Ezra', aliases: ['ezr'] },
  { num: 16, name: 'Nehemiah', abbr: 'Neh', aliases: ['ne'] },
  { num: 17, name: 'Esther', abbr: 'Esth', aliases: ['est', 'es'] },
  { num: 18, name: 'Job', abbr: 'Job', aliases: [] },
  { num: 19, name: 'Psalms', abbr: 'Ps', aliases: ['psa', 'psalm'] },
  { num: 20, name: 'Proverbs', abbr: 'Prov', aliases: ['pro', 'pr'] },
  { num: 21, name: 'Ecclesiastes', abbr: 'Eccl', aliases: ['ecc', 'ec'] },
  { num: 22, name: 'Song of Solomon', abbr: 'Song', aliases: ['so', 'ca', 'sos'] },
  { num: 23, name: 'Isaiah', abbr: 'Isa', aliases: ['iss'] },
  { num: 24, name: 'Jeremiah', abbr: 'Jer', aliases: ['je'] },
  { num: 25, name: 'Lamentations', abbr: 'Lam', aliases: ['la'] },
  { num: 26, name: 'Ezekiel', abbr: 'Ezek', aliases: ['eze'] },
  { num: 27, name: 'Daniel', abbr: 'Dan', aliases: ['da'] },
  { num: 28, name: 'Hosea', abbr: 'Hos', aliases: ['ho'] },
  { num: 29, name: 'Joel', abbr: 'Joel', aliases: ['joe'] },
  { num: 30, name: 'Amos', abbr: 'Amos', aliases: ['am'] },
  { num: 31, name: 'Obadiah', abbr: 'Obad', aliases: ['ob'] },
  { num: 32, name: 'Jonah', abbr: 'Jonah', aliases: ['jon'] },
  { num: 33, name: 'Micah', abbr: 'Mic', aliases: [] },
  { num: 34, name: 'Nahum', abbr: 'Nah', aliases: ['na'] },
  { num: 35, name: 'Habakkuk', abbr: 'Hab', aliases: [] },
  { num: 36, name: 'Zephaniah', abbr: 'Zeph', aliases: ['zep'] },
  { num: 37, name: 'Haggai', abbr: 'Hag', aliases: [] },
  { num: 38, name: 'Zechariah', abbr: 'Zech', aliases: ['zec'] },
  { num: 39, name: 'Malachi', abbr: 'Mal', aliases: [] },
  { num: 40, name: 'Matthew', abbr: 'Matt', aliases: ['mat', 'mt'] },
  { num: 41, name: 'Mark', abbr: 'Mark', aliases: ['mr', 'mk', 'mar'] },
  { num: 42, name: 'Luke', abbr: 'Luke', aliases: ['lu', 'lk', 'luk'] },
  { num: 43, name: 'John', abbr: 'John', aliases: ['joh', 'jn'] },
  { num: 44, name: 'Acts', abbr: 'Acts', aliases: ['act', 'ac'] },
  { num: 45, name: 'Romans', abbr: 'Rom', aliases: ['ro'] },
  { num: 46, name: '1 Corinthians', abbr: '1Cor', aliases: ['1co'] },
  { num: 47, name: '2 Corinthians', abbr: '2Cor', aliases: ['2co'] },
  { num: 48, name: 'Galatians', abbr: 'Gal', aliases: ['ga'] },
  { num: 49, name: 'Ephesians', abbr: 'Eph', aliases: [] },
  { num: 50, name: 'Philippians', abbr: 'Phil', aliases: ['php', 'phili'] },
  { num: 51, name: 'Colossians', abbr: 'Col', aliases: [] },
  { num: 52, name: '1 Thessalonians', abbr: '1Thess', aliases: ['1th', '1thes'] },
  { num: 53, name: '2 Thessalonians', abbr: '2Thess', aliases: ['2th', '2thes'] },
  { num: 54, name: '1 Timothy', abbr: '1Tim', aliases: ['1ti'] },
  { num: 55, name: '2 Timothy', abbr: '2Tim', aliases: ['2ti'] },
  { num: 56, name: 'Titus', abbr: 'Titus', aliases: ['tit'] },
  { num: 57, name: 'Philemon', abbr: 'Phlm', aliases: ['phm', 'phile', 'philem'] },
  { num: 58, name: 'Hebrews', abbr: 'Heb', aliases: [] },
  { num: 59, name: 'James', abbr: 'Jas', aliases: ['jam'] },
  { num: 60, name: '1 Peter', abbr: '1Pet', aliases: ['1pe'] },
  { num: 61, name: '2 Peter', abbr: '2Pet', aliases: ['2pe'] },
  { num: 62, name: '1 John', abbr: '1John', aliases: ['1jo', '1joh', '1jn'] },
  { num: 63, name: '2 John', abbr: '2John', aliases: ['2jo', '2joh', '2jn'] },
  { num: 64, name: '3 John', abbr: '3John', aliases: ['3jo', '3joh', '3jn'] },
  { num: 65, name: 'Jude', abbr: 'Jude', aliases: [] },
  { num: 66, name: 'Revelation', abbr: 'Rev', aliases: ['re'] },
];

module.exports = { BOOKS };
